"""incomplete match table

Revision ID: 0fa388ee833b
Revises: fac8e7831431
Create Date: 2025-03-21 19:57:21.156890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fa388ee833b'
down_revision = 'fac8e7831431'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opponent', sa.String(length=64), nullable=False),
    sa.Column('location', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_user_id'))
        batch_op.drop_index(batch_op.f('ix_match_timestamp'))

    op.drop_table('match')
    # ### end Alembic commands ###
